spring:
  profiles:
    active: local
  datasource:
    username: root
    url: jdbc:mysql://192.168.189.129:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    password: