spring:
  application:
    name: eureka
  security:
    user:
      name: admin
      password: 123456

server:
  port: ${Gaiety.eureka.port}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${Gaiety.eureka.host}:${Gaiety.eureka.port}/eureka
    register-with-eureka: false
    fetch-registry: false

Gaiety:
  eureka:
    host: localhost
    port: 8761